name: MiPanelApp APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Aceptar licencias
        run: yes | sdkmanager --licenses

      - name: Instalar componentes SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Instalar Gradle
        run: sudo apt-get install gradle -y

      - name: Build APK
        run: gradle assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: MiPanelApp-APK
          path: app/build/outputs/apk/debug/app-debug.apk